version: '3'

services:
  python:
    container_name: c-pytest
    volumes:
      - ./:/tmp
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    entrypoint: tail -f /dev/null 
    working_dir: /tmp
