version: '3'

services:
  python:
    container_name: c-pytest
#    volumes:
#      - ./:/tmp
    build:
      context: ./
      dockerfile: ./Dockerfile
    entrypoint: pytest 
    working_dir: /tmp
